name: Generate Changelog

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        run: npm run changelog

      - name: Complete Actions
        run: echo "Changelog generation completed successfully."
