name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            ## What's New

            * Add release notes here.  Use markdown for formatting.
            * You can use the commit messages since the last tag.

      - name: Generate Changelog
        id: changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=changelog::$(git log --pretty=format:'* %s' $(git describe --tags --abbrev=0)...${{ github.ref_name }})"
