name: GitHub Release Only
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Branch matches
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Branch matches tag"

      - name: Generate changelog
        uses: mikepenz/release-changelog-builder-action@v2

      - name: Get release tags
        run: echo "Get release tags"

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
