name: GitHub Release Only
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      APP: SSE Crypto

    steps:
      - name: Checkout git repository
        uses: actions/checkout@master

      - name: Bump version and push tag
        uses: minddocdev/mou-version-action@master
        id: bump_version
        with:
          prefix: ${{ env.APP }}@
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: minddocdev/mou-release-action@master
        with:
          app: ${{ env.APP }}
          releaseName: ${{ env.APP }} ${{ steps.bump_version.outputs.version }}
          releaseTag: ${{ steps.bump_version.outputs.tag }}
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ secrets.GITHUB_TOKEN }}
