name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }} # Use the tag name as the release name
          tag_name: ${{ github.ref_name }} # Use the tag name as the tag name
          body: |
            ## What's New

            * Add release notes here.  You can use markdown.
            * Example: Bug fixes, new features, etc.

            Full Changelog: ${{ github.ref_name }}...main # Link to a comparison page (adjust 'main' if needed)

          # Optional: Generate release notes automatically (experimental)
          # generate_release_notes: true

          # Optional: Add files to the release
          files: |
            # Path to your release artifacts
            # For example:
            dist/*.zip
            build/*.tar.gz
            # or for a single file
            # my-app.exe

          # Optional: If you want to create a draft release instead of publishing it immediately.
          # draft: true

          # Optional: Prerelease. Set to true for pre-releases.
          # prerelease: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Release Information
        if: steps.create_release.outcome == 'success'
        run: |
          echo "Release created successfully!"
          echo "Release ID: ${{ steps.create_release.outputs.id }}"
          echo "Release URL: ${{ steps.create_release.outputs.url }}"
          echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"
