name: GitHub Release Only

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      is-main: ${{ steps.is-main.outputs.result == 1 }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      version: ${{ steps.tags.outputs.new }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if releasing from main
        id: is-main
        uses: actions/branch-matches@v2
        with:
          name: main

      - name: Get tag info
        id: tags
        uses: actions/get-release-tags@v2
        with:
          prefix: "v"

      - name: Generate the changelog
        id: changelog
        uses: actions/generate-changelog@v2
        with:
          from: ${{ steps.tags.outputs.old }}
          to: ${{ steps.tags.outputs.new }}
          filter: "v"
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a draft GitHub release
        uses: actions/publish-github-release@v2
        with:
          tag: ${{ steps.tags.outputs.new }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.BOT_TOKEN }}

  github-push:
    permissions:
      contents: write # for Git to git push
    name: Push release commit to "main"
    runs-on: ubuntu-latest
    needs: github-release
    if: needs.github-release.result == 'success' && needs.github-release.outputs.is-main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update CHANGELOG.md
        uses: actions/update-changelog@v2
        with:
          changelog: ${{ needs.github-release.outputs.changelog }}
          filename: CHANGELOG.md

      - name: Commit CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git -c user.name="${{ github.actor }}" -c user.email="${{ github.actor }}@users.noreply.github.com" \
            commit -m "Add ${{ needs.github-release.outputs.version }} to CHANGELOG.md [skip ci]" --no-verify --quiet

      - name: Push to GitHub
        run: |
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main --follow-tags
